version: '3.1'

services:
  # PHP FPM with Dockerfile (don't use ports, that part is on the web server)
  php-fpm:
    build: 
      context: .
      args:
        wp_version: ${WP_VERSION}
    image: ${IMAGE_NAME}
    container_name: php-fpm
    volumes:
      - ./html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      MYSQL_CHARSET: ${MYSQL_CHARSET}
      WORDPRESS_TABLE_PREFIX: ${MYSQL_PREFIX}
      WORDPRESS_DEBUG: ${WP_DEBUG}
      WORDPRESS_CONFIG_EXTRA: |
            define('WP_DEBUG_DISPLAY', false);
            define('WP_DEBUG_LOG', true);
            define('WP_POST_REVISIONS', false);

  # MySQL
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  # Adminer
  adminer:
    image: adminer
    restart: always
    ports:
     - "${ADMINER_PORT}:8080"
    depends_on:
      - mysql

  # Nginx para servidor Web  
  web:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./html:/var/www/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf # Server conf
    container_name: matecito-nginx
    links:
      - php-fpm
    depends_on:
      - php-fpm

volumes:
  html:
  config:
  mysql:
  certs:
